spring.application.name=wallet

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Datasource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/walletdb
spring.datasource.username=walletdb
spring.datasource.password=walletdb
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Optional: Connection Pool Settings
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

#logging
logging.level.root=INFO
logging.level.com.example.wallet=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

